# Generated by Django 4.2.5 on 2023-09-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('SYMPTOM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SYMPTOM_NAME', models.CharField(max_length=255)),
                ('SYMPTOM_DESCRIPTION', models.TextField()),
                ('SEVERITY_OF_SYMPTOM', models.CharField(max_length=20)),
                ('DURATION_OF_SYMPTOM', models.CharField(max_length=20)),
            ],
        ),
    ]
