# Generated by Django 4.2.5 on 2023-09-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_patient_symptomrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIP_TITLE', models.CharField(max_length=255)),
                ('TIP_CONTENT', models.TextField()),
                ('TIP_TYPE', models.CharField(max_length=50)),
            ],
        ),
    ]
